# Docs: https://yazi-rs.github.io/docs/configuration/yazi

[opener]
edit = [
    { run = "nvim %s", block = true, desc = "NeoVim" },
]

[open]
prepend_rules = [
    { mime = "text/html", use = [ "open", "edit", "reveal" ] },
]
